### ISSUE TITLE
[BUG] Prort check for agent port runs unconditionally, even if push agent is used

### ISSUE THREAD

**Issue by hb9hnt** [Checkmk/ansible-collection-checkmk.general#437]
In version 3.2.0 a port check for TCP port 6556 is introduced in

https://github.com/Checkmk/ansible-collection-checkmk.general/blob/0925d6fd69e0d986a259e3b9d094019ce6d28148/roles/agent/tasks/Linux.yml#L106

This port check has no condition regarding whether the agent is set to push or pull mode, it runs in every case, even if the installed agent is set to push.

I'll omit the full data for my setup for now because I think it is not necessary because this bug is IMHO obvious. Please correct me if I'm wrong and I'll add all the details requested.

**Comment by robin-checkmk** [comment]
Thank you for your feedback @hb9hnt! The feature well intended and necessary for Windows host, which seem to be dragging. I thought it to be a good general feature. But I did not take the agent in push mode into consideration. I also did not take custom ports into consideration.

Do you think it makes sense to make this feature enabled by default, but configurable? Because from the top of my mind I see no easy way to learn if the agent is in push or pull mode. Of course, it is possible, but that would involve querying the Checkmk server API, which in turn might be undesirable.

**Comment by hb9hnt** [comment]
Hey @robin-checkmk - IMHO it would be ok to introduce a variable `checkmk_agent_push` or similar that can be set to true if you deploy a push agent. 

We discovered a second place where this variable can be put to use: In case of a push agent it makes sense to trigger a initial

```sh
cmk-agent-ctl push 
```

on the machine before running a discovery on Checkmk.

**Comment by hb9hnt** [comment]
@robin-checkmk No worries, I already introduced said variable in my local copy and will continue to use this until your more general approach is ready.

**Comment by robin-checkmk** [comment]
@hb9hnt if you already got something, maybe you fancy creating a PR and become a contributor? We can pan out the details in the PR then. :) No pressure, just a suggestion.

**Comment by hb9hnt** [comment]
@robin-checkmk It really just a quick and dirty variable and two checks. I can submit this as PR but I'm sure your general approach is the way to go.

**Comment by hb9hnt** [comment]
Ok, I created a PR with what I did. Feel free to turn it down and replace it with a better approach. ;)

https://github.com/Checkmk/ansible-collection-checkmk.general/pull/440

It's close to your draft. However I also threw in the initial push.
