### ISSUE TITLE
No module named error"

### ISSUE THREAD

**Issue by Fikayo93** [Checkmk/ansible-collection-checkmk.general#451]
Greetings,
I have a debian 9.0 server installation and I already installed Ansible and the required dependencies.
I have also installed the CheckMK Ansible Collection.

However, when I run the Demo Playbook " full.yml", I get the error below.

**fatal: [test1.tld -> localhost]: FAILED! => {"msg": "An unhandled exception occurred while templating '{{ lookup('checkmk.general.version', server_url + '/' + site, validate_certs=False, automation_user=automation_user, automation_secret=automation_secret) }}'. Error was a <type 'exceptions.ImportError'>, original message: No module named error"}**
 

I also edited the "auth.yml" file to have the latest supported CheckMk version for Debian9. However there is no difference.

**checkmk_version: "2.1.0p35"
checkmk_edition: "cre"**

What could be the issue here?
Thanks in anticipation of your response.

![image](https://github.com/Checkmk/ansible-collection-checkmk.general/assets/146924592/1460be67-66f1-43e7-bda9-1774c33a3dff)

**Comment by robin-checkmk** [comment]
This looks like a platform issue. But you did not use our bug report template, so I can only make educated guesses here.
1. Your OS is EOL and you should upgrade to a recent Debian version.
2. Probably due to the old OS, you might have an old Python version causing this issue.
3. Also, your Ansible version could be too old.
