### ISSUE TITLE
[FEED] How to set custom attributes / host labels?

### ISSUE THREAD

**Issue by RogerSik** [Checkmk/ansible-collection-checkmk.general#522]
Example: 

<img width="263" alt="02_13-06-30" src="https://github.com/Checkmk/ansible-collection-checkmk.general/assets/165814/da2895d7-88b1-4b55-8930-76469d53f1d4">

Setting in backend is not possible because Ansible will overwrite it and set it empty. Not sure how to set it in Ansible as variable.

**Comment by robin-checkmk** [comment]
You do not want to set labels explicitly on host or folder level. If you do so, that indicates, that you actually need a host tag. If you actually require a label, use a rule.

**Comment by RogerSik** [comment]
I think im not really understanding. I'm inherited this infrastracture and want to move it to Ansible with less changes as possible to not break something. 

> You do not want to set labels explicitly on host or folder level. If you do so, that indicates, that you actually need a host tag. If you actually require a label, use a rule.

As i understand from our environment in folders and hosts are set the labels / custom_attributes and we have already service rules which are depending of the host_labels if there is an apply. So i don't see why it is wrong / not good use case. 

Really appreciating for your help and fast feedback! :)

**Comment by robin-checkmk** [comment]
Well, it would take half a day of consulting to lay this all out, so let's get back to the issue at hand.
You have an environment that is how it is, and you want to manage it with Ansible. So far, so good.
You can of course set custom labels on host-level, you just have to put all the information in Ansible and figure out the correct syntax for the `host` module. The more long-term approach might be to actually rethink some aspects of your approach and implement that in Ansible.

All that being said: Is there a specific issue you are facing? An error or something, that we can help with here?
Otherwise, I would direct you to the [Checkmk forum](https://forum.checkmk.com/tag/ansible), for more general advice.

**Comment by RogerSik** [comment]
Yeah you are right i will going the long-term approach and rethink how this is used.
