### ISSUE TITLE
[FEED] State of checkmk.general.cluster?

### ISSUE THREAD

**Issue by HenriWahl** [Checkmk/ansible-collection-checkmk.general#673]
Hi there,

I see in https://github.com/Checkmk/ansible-collection-checkmk.general/issues/518 that the checkmk.general.cluster module is worked on. Do you have plans when it will be usable in a productive environment?

Thanks and best regards!

**Comment by robin-checkmk** [comment]
Hi @HenriWahl! There is no such module, the functionality is included in the `host` module.
Please refer to [the module documentation](https://galaxy.ansible.com/ui/repo/published/checkmk/general/content/module/host/) for details.

**Comment by HenriWahl** [comment]
@robin-checkmk meanwhile I found out how to achieve this, but I apparently was misleaded by the documentation inside the `host.py` file: https://github.com/Checkmk/ansible-collection-checkmk.general/blob/main/plugins/modules/host.py#L150

**Comment by msekania** [comment]
@robin-checkmk ,
in two place in host.py examples part
https://github.com/Checkmk/ansible-collection-checkmk.general/blob/2a422a630f548adf0e714808ca94a273a0d859b1/plugins/modules/host.py#L151
https://github.com/Checkmk/ansible-collection-checkmk.general/blob/2a422a630f548adf0e714808ca94a273a0d859b1/plugins/modules/host.py#L163

it indeed states `checkmk.general.cluster`  instead of `checkmk.general.host`

**Comment by robin-checkmk** [comment]
Thanks folks, I will fix the examples!
